### ISSUE TITLE
Issuer name does not match

### ISSUE THREAD

**Issue by ashceryth** [grimm-co/GOCSP-responder#1]
Hi,

First of all I would like to thank you for this great project - exactly what I have been looking for. However, I am facing the issue that I am unable to check the status of any certificate using `openssl ocsp` command because GOSCP is always complaining with "Issuer name does not match". Checking the same certificate with the OpenSSL OCSP Server using the same index file, CA file, rcert and rkey is working fine. What am I doing wrong?

Thank you!

**Comment by wumb0** [comment]
Strange. 
Does the CA certificate file have a cert chain in it or just one cert?
Is the CA you used to sign the certs an intermediate CA?
My initial thought is it may not handle more than one cert in the CA cert and just takes the 1st one from the file.

**Comment by ashceryth** [comment]
Indeed.
Yes, I am using a chain with Root CA and Issuing CA.
Yes, they are singed be the Issuing CA.
OK, I see. However, the Issuing CA is the first one the CA file. The CA certs are just concatenated.

**Comment by wumb0** [comment]
Try it out with just the Issuer in the CA file and let me know what happens.

**Comment by ashceryth** [comment]
Tried that and it gives me the same result. So this is very strange now.

**Comment by wumb0** [comment]
I think I know the solution. I'll push a change ASAP (within the hr) and then explain.

**Comment by ashceryth** [comment]
Great, thank you, I appreciate it.

**Comment by wumb0** [comment]
Try it out now.
I was hashing the ISSUER of the CA cert when I should have been hashing the SUBJECT.
Subject of the issuing CA and issuer of the cert you are verifying should match. Issuers matching makes no sense :|

**Comment by wumb0** [comment]
It might technically be DirName that I should validate against... rfc is not clear. I'll stick with subject unless something breaks.

From **RFC-6960**
> issuerNameHash is the hash of the issuer's distinguished name (DN).  The hash shall be calculated over the DER encoding of the issuer's name field in the certificate being checked.

¯\\_(ツ)\_/¯

**Comment by ashceryth** [comment]
Yeah, everything working fine now! Great job!
Well, now I fully understand what went wrong. The issuers can't match in my case, but they match if there's just one CA that is issued by itself.

**Comment by wumb0** [comment]
Good to hear. Yeah my testing was with a CA I created so that was not something I would have caught. Thanks for bringing it to my attention. Feel free to report other bugs or feature requests.

**Comment by ashceryth** [comment]
You're welcome. I'm using it in a test setup now and will report bugs as soon as they arise.
