### ISSUE TITLE
Panic when serving response

### ISSUE THREAD

**Issue by ashceryth** [grimm-co/GOCSP-responder#2]
Hi,

I'm facing an issue again. I tested the setup with Firefox to see if the repsonder works properly with browser requests as well. Unfortunately it does not. Requests comming from Firefox result in:

`http: panic serving 1.2.3.4:1234: runtime error: invalid memory address or nil pointer dereference`

Here is a trace from the log file:

```
2017/03/03 14:03:02 Got POST request from 1.2.3.4:1234
2017/03/03 14:03:02 Looking for serial ...
2017/03/03 14:03:02 Found entry &{...}
2017/03/03 14:03:02 This certificate is valid
2017/03/03 14:03:02 http: panic serving 1.2.3.4:1234: runtime error: invalid memory address or nil pointer dereference
goroutine XX [running]:
net/http.(*conn).serve.func1(...)
        /path/to/go/src/net/http/server.go:1721 ...
panic(...)
        /path/to/go/src/runtime/panic.go:489 ...
gocsp-responder/responder.(*OCSPResponder).verify(...)
        /path/to/gocsp-responder/responder/responder.go:307 ...
gocsp-responder/responder.(*OCSPResponder).makeHandler.func1(...)
        /path/to/gocsp-responder/responder/responder.go:100 ...
net/http.HandlerFunc.ServeHTTP(...)
        /path/to/go/src/net/http/server.go:1942 ...
net/http.(*ServeMux).ServeHTTP(...)
        /path/to/go/src/net/http/server.go:2238 ...
net/http.serverHandler.ServeHTTP(...)
        /path/to/go/src/net/http/server.go:2568 ...
net/http.(*conn).serve(...)
        /path/to/go/src/net/http/server.go:1825 ...
created by net/http.(*Server).Serve
        /path/to/go/src/net/http/server.go:2668 ...
```

The same happens with GET requests comming from Microsoft CryptoAPI.

Please let me know if you need any further information.

Thanks!

**Comment by wumb0** [comment]
Looks like when I added nonce list checking I put the null check too low. It **should** be ok now.

**Comment by wumb0** [comment]
Working now on my end :)
Let me know if that fixes the issue for you. 
That was the last thing I added to the code. It worked with openssl ocsp because it includes the nonce. Most browsers do not.

**Comment by ashceryth** [comment]
Working for me as well 👍
Everything looking good so far. Even GET requests by the MS CryptoAPI appear to be working fine now.
Thanks for the quick bugfix!
