### ISSUE TITLE
Issue with serials longer than 8 byte

### ISSUE THREAD

**Issue by ashceryth** [grimm-co/GOCSP-responder#5]
Hi,

I was just testing with a certificate with a 16 bytes serial number using ```openssl ocsp``` command. In the responder log I can see: ```Looking for serial 0xa737f5dbf1d133b3``` In fact the serial is twice the size. The first 8 bytes seem to be cut off. Therefore the verification fails. Is this an issue with the responder or openssl? It works just fine if i remove the first 8 bytes in the index file.

Thanks!

EDIT: Corrected "bits" to "bytes"

**Comment by wumb0** [comment]
I have a ParseUint with 64 as the bit length so it should be fine with up to 64-bits (8 bytes).
I assume you mean 16 bytes, so in that case I'll just push a fix doubling that number to 128 bits and that should fix your issue. Give me 5 to test.

**Comment by wumb0** [comment]
Eh ill have to switch to BigInt.

**Comment by ashceryth** [comment]
Thanks for your super fast response! Yes, I mean 16 bytes of course, sorry. I think RFC 5280 says that serials must not be longer than 20 bytes. Maybe it would be decent to handle serials up to that size.

**Comment by wumb0** [comment]
I closed it but I haven't tested it... if you would be so kind :)
Also, funny because I left myself a comment in the code two years ago (if you look at the commit) that says the serial should probably be a big.Int.

**Comment by ashceryth** [comment]
Hmmm, I can't install it.

```
# go install gocsp-responder/main
# gocsp-responder/responder
src/gocsp-responder/responder/responder.go:157:18: cannot assign *big.Int to ie.Serial (type big.Int) in multiple assignment
src/gocsp-responder/responder/responder.go:161:18: cannot assign *big.Int to ie.Serial (type big.Int) in multiple assignment
src/gocsp-responder/responder/responder.go:184:17: invalid operation: ent.Serial == s (mismatched types big.Int and uint64)
```

**Comment by wumb0** [comment]
aw jeeze, i thought it built over here. my go env must be a bit rusty. 
please hold.

**Comment by wumb0** [comment]
8d25aa7c7b8d should do it. let me know if there's issues.

**Comment by wumb0** [comment]
One more push fixing a logic bug, needed .Cmp instead of ==

**Comment by ashceryth** [comment]
Fantastic, everything works now! My certs with 16 byte serials can be checked. Thanks a bunch!
